question_data = [
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Board Games",
     "question": "Carcassonne is based on which French town?", "correct_answer": "Carcassonne",
     "incorrect_answers": ["Paris", "Marseille", "Clermont-Ferrand"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "The 2010 film &quot;The Social Network&quot; is a biographical drama film about MySpace founder Tom Anderson.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Musicals &amp; Theatres",
     "question": "IMAX stands for Image Maximum.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "What was Daft Punk&#039;s first studio album?", "correct_answer": "Homework",
     "incorrect_answers": ["Discovery", "Random Access Memories", "Human After All"]},
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
     "question": "What is the closest planet to our solar system&#039;s sun?", "correct_answer": "Mercury",
     "incorrect_answers": ["Mars", "Jupiter", "Earth"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Books",
     "question": "Under what pseudonym did Stephen King publish five novels between 1977 and 1984?",
     "correct_answer": "Richard Bachman", "incorrect_answers": ["J. D. Robb", "Mark Twain", "Lewis Carroll"]},
    {"type": "multiple", "difficulty": "easy", "category": "Sports",
     "question": "Which country hosted the 2018 FIFA World Cup?", "correct_answer": "Russia",
     "incorrect_answers": ["Germany", "United States", "Saudi Arabia"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "easy", "category": "General Knowledge",
     "question": "How tall is the Burj Khalifa?", "correct_answer": "2,722 ft",
     "incorrect_answers": ["2,717 ft", "2,546 ft", "3,024 ft"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "In the 1992 film &quot;Army of Darkness&quot;, what name does Ash give to his double-barreled shotgun?",
     "correct_answer": "Boomstick", "incorrect_answers": ["Bloomstick", "Blastbranch", "2-Pump Chump"]}]
